#!/bin/bash

# Script to help create a GitHub token with correct GHCR permissions
echo "🔑 Creating GitHub Token for Container Registry"
echo "============================================="

echo "📋 You need a GitHub Personal Access Token with these scopes:"
echo ""
echo "✅ Required Scopes:"
echo "   • repo (Full control of private repositories)"
echo "   • write:packages (Upload packages to GitHub Package Registry)"
echo "   • read:packages (Download packages from GitHub Package Registry)"
echo "   • delete:packages (Delete packages from GitHub Package Registry)"
echo ""
echo "🔗 Create your token here:"
echo "   https://github.com/settings/tokens/new"
echo ""
echo "📝 Token Settings:"
echo "   • Token name: 'python-mcp-server-ghcr'"
echo "   • Expiration: Choose your preference (30 days, 90 days, etc.)"
echo "   • Scopes: Check ALL the boxes above"
echo ""
echo "⚠️  IMPORTANT: Copy the token immediately - you won't see it again!"
echo ""
echo "🔄 After creating the token:"
echo "   1. Copy the new token"
echo "   2. Update your ~/.zshrc file:"
echo "      export PYTHON_MCP_SERVER_GHCR_TOKEN='your_new_token_here'"
echo "   3. Source your zshrc: source ~/.zshrc"
echo "   4. Run: ./test-new-ghcr-token.sh"
echo ""
echo "🎯 This will fix the 401 Unauthorized error!"