#!/bin/bash

# Script to help create a new GitHub token and fix authentication
echo "🔑 Creating New GitHub Token and Fixing Authentication"
echo "===================================================="

echo "❌ Current token is invalid or expired (401 Bad credentials)"
echo ""
echo "🔧 Let's create a new GitHub token with proper permissions:"
echo ""
echo "📝 Steps to create a new token:"
echo "1. Go to: https://github.com/settings/tokens"
echo "2. Click 'Generate new token' > 'Generate new token (classic)'"
echo "3. Give it a name like 'Kubernetes GHCR Access'"
echo "4. Set expiration (recommend 90 days or no expiration for testing)"
echo "5. Select these scopes:"
echo "   ✅ repo (Full control of private repositories)"
echo "   ✅ packages:read (Download packages from GitHub Package Registry)"
echo "   ✅ packages:write (Upload packages to GitHub Package Registry)"
echo "6. Click 'Generate token'"
echo "7. Copy the token (it starts with ghp_)"
echo ""
echo "💡 Alternative: Use a fine-grained personal access token:"
echo "1. Go to: https://github.com/settings/personal-access-tokens/fine-grained"
echo "2. Click 'Generate new token'"
echo "3. Select your repository: hawaiideveloper/python-mcp-server"
echo "4. Select permissions: Contents (Read), Packages (Read)"
echo "5. Generate and copy the token"
echo ""
echo "🔧 Once you have a new token, run:"
echo "   export GITHUB_TOKEN=your_new_token_here"
echo "   ./test-new-token.sh"
echo ""
echo "📋 Current deployment status:"
kubectl get pods -n python-mcp-server
kubectl get svc -n python-mcp-server
echo ""
echo "⏳ Current deployment is still trying to pull with invalid token..."
echo "💡 We'll fix this once you have a new token!"