#!/bin/bash

# Manual deployment commands for Python MCP Server to Kubernetes
# Run these commands in your working terminal that can connect to Kubernetes

echo "🚀 Manual Deployment Commands for Python MCP Server"
echo "=================================================="
echo ""
echo "1. First, navigate to the project directory:"
echo "   cd /Users/hawaiideveloper/Documents/github/python-mcp-server"
echo ""
echo "2. Make sure you're on the kubernetes-only branch:"
echo "   git checkout kubernetes-only"
echo ""
echo "3. Verify Kubernetes connectivity:"
echo "   kubectl get nodes"
echo ""
echo "4. Deploy the test version:"
echo "   kubectl create namespace mcp-server-test --dry-run=client -o yaml | kubectl apply -f -"
echo "   kubectl apply -f k8s-test-deployment.yaml -n mcp-server-test"
echo ""
echo "5. Check deployment status:"
echo "   kubectl get pods -n mcp-server-test"
echo "   kubectl get svc -n mcp-server-test"
echo ""
echo "6. Check pod logs:"
echo "   kubectl logs -l app=python-mcp-server -n mcp-server-test --tail=20"
echo ""
echo "7. Test the service (port-forward):"
echo "   kubectl port-forward svc/python-mcp-server-test-service 8080:80 -n mcp-server-test"
echo "   # Then test: curl http://localhost:8080/health"
echo ""
echo "8. If test works, deploy production version:"
echo "   kubectl create namespace mcp-server --dry-run=client -o yaml | kubectl apply -f -"
echo "   kubectl apply -f k8s-production-deployment.yaml"
echo ""
echo "9. Check production deployment:"
echo "   kubectl get pods -n mcp-server"
echo "   kubectl get svc -n mcp-server"
echo ""
echo "10. Get LoadBalancer external IP:"
echo "    kubectl get svc python-mcp-server-service -n mcp-server -o wide"
echo ""
echo "=================================================="
echo "🎉 Copy and paste these commands into your working terminal!"